USE [GD2C2020]
GO

	IF OBJECT_ID('FFAN.BI_COMPRAS', 'U') IS NOT NULL DROP TABLE [FFAN].[BI_COMPRAS];
GO
	IF OBJECT_ID('FFAN.BI_VENTAS', 'U') IS NOT NULL DROP TABLE [FFAN].[BI_VENTAS];
GO
	IF OBJECT_ID('FFAN.BI_SUCURSAL', 'U') IS NOT NULL DROP TABLE [FFAN].[BI_SUCURSAL]
GO
	IF OBJECT_ID('FFAN.BI_MODELO', 'U') IS NOT NULL DROP TABLE [FFAN].[BI_MODELO]
GO
	IF OBJECT_ID('FFAN.BI_FABRICANTE', 'U') IS NOT NULL DROP TABLE [FFAN].[BI_FABRICANTE]
GO
	IF OBJECT_ID('FFAN.BI_TIPO_CAJA', 'U') IS NOT NULL DROP TABLE [FFAN].[BI_TIPO_CAJA]
GO
	IF OBJECT_ID('FFAN.BI_TIPO_AUTOMOVIL', 'U') IS NOT NULL DROP TABLE [FFAN].[BI_TIPO_AUTOMOVIL]
GO
	IF OBJECT_ID('FFAN.BI_AUTOPARTE', 'U') IS NOT NULL DROP TABLE [FFAN].[BI_AUTOPARTE];
GO
	IF OBJECT_ID('FFAN.BI_RUBRO_AUTOPARTE', 'U') IS NOT NULL DROP TABLE [FFAN].[BI_RUBRO_AUTOPARTE]
GO
	IF OBJECT_ID('FFAN.BI_POTENCIA', 'U') IS NOT NULL DROP TABLE [FFAN].[BI_POTENCIA]
GO
	IF OBJECT_ID('FFAN.BI_TIEMPO', 'U') IS NOT NULL DROP TABLE [FFAN].[BI_TIEMPO];

GO
	IF OBJECT_ID('FFAN.BI_CANTIDAD_CAMBIOS', 'U') IS NOT NULL DROP TABLE [FFAN].[BI_CANTIDAD_CAMBIOS];

GO
	IF OBJECT_ID('FFAN.BI_TIPO_MOTOR', 'U') IS NOT NULL DROP TABLE [FFAN].[BI_TIPO_MOTOR];

GO
	IF OBJECT_ID('FFAN.BI_TIPO_TRANSMISION', 'U') IS NOT NULL DROP TABLE [FFAN].[BI_TIPO_TRANSMISION];

GO
	IF OBJECT_ID('FFAN.BI_TIPO_AUTOMOVIL', 'U') IS NOT NULL DROP TABLE [FFAN].[BI_TIPO_AUTOMOVIL];

GO
	IF OBJECT_ID('FFAN.BI_CLIENTE', 'U') IS NOT NULL DROP TABLE [FFAN].[BI_CLIENTE];

GO
	IF OBJECT_ID('FFAN.BI_RANGO_ETARIO', 'U') IS NOT NULL DROP TABLE [FFAN].[BI_RANGO_ETARIO];

GO

	CREATE TABLE [FFAN].[BI_SUCURSAL](
		SUCURSAL_ID DECIMAL(18, 0) NOT NULL PRIMARY KEY,
		SUCURSAL_DIRECCION NVARCHAR(255),
		SUCURSAL_MAIL NVARCHAR(255),
		SUCURSAL_TELEFONO DECIMAL(18, 0),
		SUCURSAL_CIUDAD NVARCHAR(255)
	)
GO

	CREATE TABLE [FFAN].[BI_MODELO] (
		MODELO_ID DECIMAL(18, 0) NOT NULL PRIMARY KEY,
		MODELO_NOMBRE NVARCHAR(255),
		MODELO_POTENCIA DECIMAL(18, 0)
	)
GO

	CREATE TABLE [FFAN].[BI_FABRICANTE] (
		FABRICANTE_ID DECIMAL(18, 0) NOT NULL  PRIMARY KEY,
		FABRICANTE_NOMBRE NVARCHAR(255)
	)
GO

	CREATE TABLE [FFAN].[BI_TIPO_CAJA] (
		TIPO_CAJA_ID DECIMAL(18, 0) NOT NULL PRIMARY KEY,
		TIPO_CAJA_DESCRIPCION NVARCHAR(255)
	)
GO
	CREATE TABLE [FFAN].[BI_TIPO_AUTOMOVIL] (
		TIPO_AUTOMOVIL_ID DECIMAL(18, 0) NOT NULL PRIMARY KEY,
		TIPO_AUTOMOVIL_DESCRIPCION NVARCHAR(255)
	)
GO

	CREATE TABLE [FFAN].[BI_RUBRO_AUTOPARTE] (
		RUBRO_AUTOPARTE_ID DECIMAL(18, 0) NOT NULL PRIMARY KEY,
		RUBRO_AUTOPARTE_DESCRIPCION NVARCHAR(255)
	)
GO


	CREATE TABLE [FFAN].[BI_AUTOPARTE] (
		AUTOPARTE_ID DECIMAL(18, 0) NOT NULL PRIMARY KEY,
		AUTOPARTE_DESCRIPCION NVARCHAR(255),
		AUTOPARTE_RUBRO_ID DECIMAL(18, 0) FOREIGN KEY REFERENCES FFAN.BI_RUBRO_AUTOPARTE(RUBRO_AUTOPARTE_ID)
	)
GO

	CREATE TABLE [FFAN].[BI_POTENCIA] (
		POTENCIA_ID DECIMAL(18, 0) NOT NULL IDENTITY(1, 1) PRIMARY KEY,
		POTENCIA_DESCRIPCION NVARCHAR(255)
	)
GO

	CREATE TABLE [FFAN].[BI_TIEMPO] (
		TIEMPO_ID DECIMAL(18, 0) NOT NULL IDENTITY(1, 1) PRIMARY KEY,
		TIEMPO_ANIO DECIMAL(4,0) NOT NULL,
		TIEMPO_MES DECIMAL(2,0) NOT NULL
	)
GO

	CREATE TABLE [FFAN].[BI_TIPO_TRANSMISION] (
		TIPO_TRANSMISION_ID DECIMAL(18, 0) NOT NULL PRIMARY KEY,
		TIPO_TRANSMISION_DESCRIPCION NVARCHAR(255)
	)
GO

	CREATE TABLE [FFAN].[BI_TIPO_MOTOR] (
		TIPO_MOTOR_ID DECIMAL(18, 0) NOT NULL PRIMARY KEY,
		TIPO_MOTOR_DESCRIPCION NVARCHAR(255)
	)
GO

	CREATE TABLE [FFAN].[BI_CANTIDAD_CAMBIOS] (
		CANTIDAD_CAMBIOS_ID DECIMAL(18, 0) IDENTITY(1,1) NOT NULL PRIMARY KEY,
		CANTIDAD_CAMBIOS_NRO DECIMAL(2,0)
	)
GO


	CREATE TABLE [FFAN].[BI_RANGO_ETARIO] (
		RANGO_ETARIO_ID DECIMAL(2, 0) NOT NULL IDENTITY(1, 1) PRIMARY KEY,
		RANGO_ETARIO_DESCRIPCION NVARCHAR(30)
	)
GO

	CREATE TABLE [FFAN].[BI_CLIENTE] (
		CLIENTE_ID DECIMAL(18, 0) NOT NULL PRIMARY KEY,
		CLIENTE_SEXO NVARCHAR(1),
		CLIENTE_RANGO_ETARIO_ID DECIMAL(2, 0) FOREIGN KEY REFERENCES FFAN.BI_RANGO_ETARIO(RANGO_ETARIO_ID)
	)
GO

	CREATE TABLE [FFAN].[BI_COMPRAS] (
		COMPRAS_TIEMPO_ID DECIMAL(18, 0) FOREIGN KEY REFERENCES FFAN.BI_TIEMPO(TIEMPO_ID),
		COMPRAS_CLIENTE_ID DECIMAL(18, 0) FOREIGN KEY REFERENCES FFAN.BI_CLIENTE(CLIENTE_ID),
		COMPRAS_SUCURSAL_ID DECIMAL(18, 0) FOREIGN KEY REFERENCES FFAN.BI_SUCURSAL(SUCURSAL_ID),
		COMPRAS_MODELO_ID DECIMAL(18, 0) FOREIGN KEY REFERENCES FFAN.BI_MODELO(MODELO_ID),
		COMPRAS_FABRICANTE_ID DECIMAL(18, 0) FOREIGN KEY REFERENCES FFAN.BI_FABRICANTE(FABRICANTE_ID),
		COMPRAS_TIPO_CAJA_ID DECIMAL(18, 0) FOREIGN KEY REFERENCES FFAN.BI_TIPO_CAJA(TIPO_CAJA_ID),
		COMPRAS_TIPO_AUTOMOVIL_ID DECIMAL(18, 0) FOREIGN KEY REFERENCES FFAN.BI_TIPO_AUTOMOVIL(TIPO_AUTOMOVIL_ID),
		COMPRAS_AUTOPARTE_ID DECIMAL(18, 0) FOREIGN KEY REFERENCES FFAN.BI_AUTOPARTE(AUTOPARTE_ID),
		COMPRAS_POTENCIA_ID DECIMAL(18, 0) FOREIGN KEY REFERENCES FFAN.BI_POTENCIA(POTENCIA_ID),
		COMPRAS_TIPO_TRANSMISION_ID DECIMAL(18, 0) FOREIGN KEY REFERENCES FFAN.BI_TIPO_TRANSMISION(TIPO_TRANSMISION_ID),
		COMPRAS_TIPO_MOTOR_ID DECIMAL(18, 0) FOREIGN KEY REFERENCES FFAN.BI_TIPO_MOTOR(TIPO_MOTOR_ID),
		COMPRAS_CANTIDAD_CAMBIOS_ID DECIMAL(18, 0) FOREIGN KEY REFERENCES FFAN.BI_CANTIDAD_CAMBIOS(CANTIDAD_CAMBIOS_ID),
		COMPRAS_AUTOMOVILES_UNIDADES DECIMAL(18,0) NOT NULL,
		COMPRAS_AUTOMOVILES_IMPORTE DECIMAL(18,2) NOT NULL,
		COMPRAS_AUTOPARTES_UNIDADES DECIMAL(18,0) NOT NULL,
		COMPRAS_AUTOPARTES_IMPORTE DECIMAL(18,2) NOT NULL
	)
GO


	CREATE TABLE [FFAN].[BI_VENTAS] (
		VENTAS_TIEMPO_ID DECIMAL(18, 0) FOREIGN KEY REFERENCES FFAN.BI_TIEMPO(TIEMPO_ID),
		VENTAS_CLIENTE_ID DECIMAL(18, 0) FOREIGN KEY REFERENCES FFAN.BI_CLIENTE(CLIENTE_ID),
		VENTAS_SUCURSAL_ID DECIMAL(18, 0) FOREIGN KEY REFERENCES FFAN.BI_SUCURSAL(SUCURSAL_ID),
		VENTAS_MODELO_ID DECIMAL(18, 0) FOREIGN KEY REFERENCES FFAN.BI_MODELO(MODELO_ID),
		VENTAS_FABRICANTE_ID DECIMAL(18, 0) FOREIGN KEY REFERENCES FFAN.BI_FABRICANTE(FABRICANTE_ID),
		VENTAS_TIPO_CAJA_ID DECIMAL(18, 0) FOREIGN KEY REFERENCES FFAN.BI_TIPO_CAJA(TIPO_CAJA_ID),
		VENTAS_TIPO_AUTOMOVIL_ID DECIMAL(18, 0) FOREIGN KEY REFERENCES FFAN.BI_TIPO_AUTOMOVIL(TIPO_AUTOMOVIL_ID),
		VENTAS_AUTOPARTE_ID DECIMAL(18, 0) FOREIGN KEY REFERENCES FFAN.BI_AUTOPARTE(AUTOPARTE_ID),
		VENTAS_POTENCIA_ID DECIMAL(18, 0) FOREIGN KEY REFERENCES FFAN.BI_POTENCIA(POTENCIA_ID),
		VENTAS_TIPO_TRANSMISION_ID DECIMAL(18, 0) FOREIGN KEY REFERENCES FFAN.BI_TIPO_TRANSMISION(TIPO_TRANSMISION_ID),
		VENTAS_TIPO_MOTOR_ID DECIMAL(18, 0) FOREIGN KEY REFERENCES FFAN.BI_TIPO_MOTOR(TIPO_MOTOR_ID),
		VENTAS_CANTIDAD_CAMBIOS_ID DECIMAL(18, 0) FOREIGN KEY REFERENCES FFAN.BI_CANTIDAD_CAMBIOS(CANTIDAD_CAMBIOS_ID),
		VENTAS_AUTOMOVILES_UNIDADES DECIMAL(18,0) NOT NULL,
		VENTAS_AUTOMOVILES_IMPORTE DECIMAL(18,2) NOT NULL,
		VENTAS_AUTOPARTES_UNIDADES DECIMAL(18,0) NOT NULL,
		VENTAS_AUTOPART_IMPORTE DECIMAL(18,2) NOT NULL
	)
GO

/* 
   FEDE
	CREATE TABLE [FFAN].[BI_SUCURSAL](
	CREATE TABLE [FFAN].[BI_MODELO] (
	CREATE TABLE [FFAN].[BI_FABRICANTE] (
	CREATE TABLE [FFAN].[BI_TIPO_CAJA] (

FACU
	CREATE TABLE [FFAN].[BI_TIPO_AUTOMOVIL] (
	CREATE TABLE [FFAN].[BI_RUBRO_AUTOPARTE] (
    CREATE TABLE [FFAN].[BI_AUTOPARTE] (

NACHO
	CREATE TABLE [FFAN].[BI_POTENCIA] (
	CREATE TABLE [FFAN].[BI_TIEMPO] (
	CREATE TABLE [FFAN].[BI_TIPOTRANSMISION] (

ALEXIS
	CREATE TABLE [FFAN].[BI_TIPO_MOTOR] (
	CREATE TABLE [FFAN].[BI_CANTIDAD_CAMBIOS] (
	CREATE TABLE [FFAN].[BI_RANGOETARIO] (
	CREATE TABLE [FFAN].[BI_CLIENTE] (
	
	
DISCUTIMOS MEJOR OPCION EL LUNES
	CREATE TABLE [FFAN].[BI_COMPRAS] (
	CREATE TABLE [FFAN].[BI_VENTAS] (


*/



INSERT INTO
	FFAN.BI_TIPO_AUTOMOVIL
SELECT
	TIPO_AUTO_CODIGO,
	TIPO_AUTO_DESC
FROM
	FFAN.TIPO_AUTO
GO

/*SE PONE NULL EN RUBRO HAST AQUE ENTANDAMOS A QUE SE REFIERE EL RUBRO */
INSERT INTO
	FFAN.BI_AUTOPARTE
SELECT
	AUTOPARTE_CODIGO,
	AUTOPARTE_DESCRIPCION,
	NULL
FROM
	FFAN.AUTOPARTE
GO

/* INSERTS ALEXIS */
INSERT
	INTO
	FFAN.BI_CANTIDAD_CAMBIOS (CANTIDAD_CAMBIOS_NRO)
VALUES (NULL)
GO


INSERT
	INTO
	FFAN.BI_TIPO_MOTOR
SELECT
	TM.TIPO_MOTOR_CODIGO,
	TM.TIPO_MOTOR_DESC
FROM
	FFAN.TIPO_MOTOR TM
GO


INSERT INTO FFAN.BI_RANGO_ETARIO (RANGO_ETARIO_DESCRIPCION ) VALUES ('18 A 30 AÑOS')
GO
INSERT INTO FFAN.BI_RANGO_ETARIO (RANGO_ETARIO_DESCRIPCION ) VALUES ('31 A 50 AÑOS')
GO
INSERT INTO FFAN.BI_RANGO_ETARIO (RANGO_ETARIO_DESCRIPCION ) VALUES ('MAYOR DE 50 AÑOS')
GO
INSERT INTO FFAN.BI_RANGO_ETARIO (RANGO_ETARIO_DESCRIPCION ) VALUES ('SIN INFORMACIÓN')
GO

INSERT
	INTO
	FFAN.BI_CLIENTE (CLIENTE_ID, CLIENTE_SEXO, CLIENTE_RANGO_ETARIO_ID )
SELECT
	C.CLIENTE_ID,
	NULL,
	CASE
		WHEN FLOOR(DATEDIFF(DAY, C.CLIENTE_FECHA_NAC, GETDATE())/ 365.2425) BETWEEN 18 AND 30 THEN 1
		WHEN FLOOR(DATEDIFF(DAY, C.CLIENTE_FECHA_NAC, GETDATE())/ 365.2425) BETWEEN 31 AND 50 THEN 2
		WHEN FLOOR(DATEDIFF(DAY, C.CLIENTE_FECHA_NAC, GETDATE())/ 365.2425) > 50 THEN 3
		ELSE 4
	END
FROM
	FFAN.CLIENTE C
GO
	
SELECT * FROM FFAN.BI_Cliente bc 
	