USE [GD2C2020]
GO

IF NOT EXISTS ( SELECT  *
                FROM    sys.schemas
                WHERE   name = N'FFAN' )
    EXEC('CREATE SCHEMA [FFAN]');
GO
	IF OBJECT_ID('FFAN.ITEM_COMPRA_AUTOMOVIL', 'U') IS NOT NULL DROP TABLE [FFAN].[ITEM_COMPRA_AUTOMOVIL]
GO
	IF OBJECT_ID('FFAN.ITEM_COMPRA_AUTOPARTE', 'U') IS NOT NULL DROP TABLE [FFAN].[ITEM_COMPRA_AUTOPARTE]
GO
	IF OBJECT_ID('FFAN.COMPRA', 'U') IS NOT NULL DROP TABLE [FFAN].[COMPRA]
GO
	IF OBJECT_ID('FFAN.ITEM_FACTURA_AUTOMOVIL', 'U') IS NOT NULL DROP TABLE [FFAN].[ITEM_FACTURA_AUTOMOVIL]
GO
	IF OBJECT_ID('FFAN.ITEM_FACTURA_AUTOPARTE', 'U') IS NOT NULL DROP TABLE [FFAN].[ITEM_FACTURA_AUTOPARTE]
GO
	IF OBJECT_ID('FFAN.FACTURA', 'U') IS NOT NULL DROP TABLE [FFAN].[FACTURA]
GO
	IF OBJECT_ID('FFAN.AUTOMOVIL', 'U') IS NOT NULL DROP TABLE [FFAN].[AUTOMOVIL];

GO
	IF OBJECT_ID('FFAN.AUTOPARTE', 'U') IS NOT NULL DROP TABLE [FFAN].[AUTOPARTE]
GO
	IF OBJECT_ID('FFAN.TIPO_CAJA', 'U') IS NOT NULL DROP TABLE [FFAN].[TIPO_CAJA];

GO
	IF OBJECT_ID('FFAN.TIPO_TRANSMISION', 'U') IS NOT NULL DROP TABLE [FFAN].[TIPO_TRANSMISION];

GO
	IF OBJECT_ID('FFAN.TIPO_MOTOR', 'U') IS NOT NULL DROP TABLE [FFAN].[TIPO_MOTOR];

GO
	IF OBJECT_ID('FFAN.TIPO_AUTO', 'U') IS NOT NULL DROP TABLE [FFAN].[TIPO_AUTO];

GO
	IF OBJECT_ID('FFAN.MODELO', 'U') IS NOT NULL DROP TABLE [FFAN].[MODELO];

GO
	IF OBJECT_ID('FFAN.FABRICANTE', 'U') IS NOT NULL DROP TABLE [FFAN].[FABRICANTE];

GO
	IF OBJECT_ID('FFAN.CLIENTE', 'U') IS NOT NULL DROP TABLE [FFAN].[CLIENTE];

GO
	IF OBJECT_ID('FFAN.SUCURSAL', 'U') IS NOT NULL DROP TABLE [FFAN].[SUCURSAL];

GO
	CREATE TABLE [FFAN].[TIPO_CAJA] (
		TIPO_CAJA_CODIGO DECIMAL(18, 0) NOT NULL PRIMARY KEY,
		/* VERIFICAR SI DEBERIA EMPEZAR POR 1000 EN VEZ DE 1 */
		TIPO_CAJA_DESC NVARCHAR(255)
	)
GO
	CREATE TABLE [FFAN].[TIPO_TRANSMISION] (
		TIPO_TRANSMISION_CODIGO DECIMAL(18, 0) NOT NULL PRIMARY KEY,
		TIPO_TRANSMISION_DESC NVARCHAR(255)
	)
GO
	CREATE TABLE [FFAN].[TIPO_MOTOR] (
		TIPO_MOTOR_CODIGO DECIMAL(18, 0) NOT NULL PRIMARY KEY,
		TIPO_MOTOR_DESC NVARCHAR(255)
	)
GO
	CREATE TABLE [FFAN].[TIPO_AUTO] (
		TIPO_AUTO_CODIGO DECIMAL(18, 0) NOT NULL PRIMARY KEY,
		TIPO_AUTO_DESC NVARCHAR(255)
	)
GO
	CREATE TABLE [FFAN].[MODELO] (
		MODELO_CODIGO DECIMAL(18, 0) NOT NULL PRIMARY KEY,
		MODELO_NOMBRE NVARCHAR(255),
		MODELO_POTENCIA DECIMAL(18, 0)
	)
GO
	CREATE TABLE [FFAN].[FABRICANTE] (
		FABRICANTE_CODIGO DECIMAL(18, 0) NOT NULL IDENTITY(1, 1) PRIMARY KEY,
		FABRICANTE_NOMBRE NVARCHAR(255)
	)
GO
	CREATE TABLE [FFAN].[CLIENTE] (
		CLIENTE_ID DECIMAL(18, 0) NOT NULL IDENTITY(1, 1) PRIMARY KEY,
		CLIENTE_APELLIDO NVARCHAR(255) NOT NULL,
		CLIENTE_NOMBRE NVARCHAR(255) NOT NULL,
		CLIENTE_DIRECCION NVARCHAR(255) NOT NULL,
		CLIENTE_DNI DECIMAL(18, 0) NOT NULL,
		CLIENTE_FECHA_NAC DATETIME2(3) NOT NULL,
		CLIENTE_EMAIL NVARCHAR(255),
	)
GO
	CREATE TABLE [FFAN].[SUCURSAL](
		SUCURSAL_ID DECIMAL(18, 0) NOT NULL IDENTITY(1, 1) PRIMARY KEY,
		SUCURSAL_DIRECCION NVARCHAR(255),
		SUCURSAL_MAIL NVARCHAR(255),
		SUCURSAL_TELEFONO DECIMAL(18, 0),
		SUCURSAL_CIUDAD NVARCHAR(255)
	)
GO
	CREATE TABLE [FFAN].[AUTOPARTE] (
		AUTOPARTE_CODIGO DECIMAL(18, 0) NOT NULL PRIMARY KEY,
		AUTOPARTE_DESCRIPCION NVARCHAR(255),
		AUTOPARTE_FABRICANTE_CODIGO DECIMAL(18, 0) NOT NULL FOREIGN KEY REFERENCES FFAN.FABRICANTE(FABRICANTE_CODIGO),
		AUTOPARTE_MODELO_CODIGO DECIMAL(18, 0)
	)
GO
	CREATE TABLE [FFAN].[AUTOMOVIL] (
		AUTO_ID DECIMAL(18, 0) NOT NULL IDENTITY(1, 1) PRIMARY KEY,
		AUTO_PATENTE NVARCHAR(50) NOT NULL,
		AUTO_FECHA_ALTA DATETIME2(2) NOT NULL,
		AUTO_CANT_KMS DECIMAL(18, 0) NOT NULL,
		AUTO_NRO_CHASIS NVARCHAR(50) NOT NULL,
		AUTO_NRO_MOTOR NVARCHAR(50) NOT NULL,
		AUTO_MODELO_CODIGO DECIMAL(18, 0) FOREIGN KEY REFERENCES FFAN.MODELO(MODELO_CODIGO),
		AUTO_TIPO_CAJA_CODIGO DECIMAL(18, 0) FOREIGN KEY REFERENCES FFAN.TIPO_CAJA(TIPO_CAJA_CODIGO),
		AUTO_TIPO_MOTOR_CODIGO DECIMAL(18, 0) FOREIGN KEY REFERENCES FFAN.TIPO_MOTOR(TIPO_MOTOR_CODIGO),
		AUTO_TIPO_TRANSMISION DECIMAL(18, 0) FOREIGN KEY REFERENCES FFAN.TIPO_TRANSMISION(TIPO_TRANSMISION_CODIGO),
		AUTO_TIPO_CODIGO DECIMAL(18, 0) FOREIGN KEY REFERENCES FFAN.TIPO_AUTO(TIPO_AUTO_CODIGO),
		AUTO_FABRICANTE_CODIGO DECIMAL(18, 0) FOREIGN KEY REFERENCES FFAN.FABRICANTE(FABRICANTE_CODIGO)
	)
GO
	CREATE TABLE [FFAN].[COMPRA] (
		COMPRA_NRO DECIMAL(18, 0) NOT NULL PRIMARY KEY,
		COMPRA_FECHA DATETIME2(3),
		COMPRA_CLIENTE DECIMAL(18, 0) FOREIGN KEY REFERENCES FFAN.CLIENTE(CLIENTE_ID),
		COMPRA_PRECIO_TOTAL DECIMAL(18, 2),
		COMPRA_SUCURSAL_ID DECIMAL(18, 0) NOT NULL FOREIGN KEY REFERENCES FFAN.SUCURSAL(SUCURSAL_ID),
		COMPRA_SUCURSAL_DIRECCION NVARCHAR(255),
		COMPRA_SUCURSAL_CIUDAD NVARCHAR(255)
	)
GO
	CREATE TABLE [FFAN].[ITEM_COMPRA_AUTOMOVIL] (
		ITEM_COMPRA_AUTO_NRO DECIMAL(18, 0) NOT NULL FOREIGN KEY REFERENCES FFAN.COMPRA(COMPRA_NRO),
		ITEM_COMPRA_AUTO_ID DECIMAL(18, 0) NOT NULL FOREIGN KEY REFERENCES FFAN.AUTOMOVIL(AUTO_ID),
		ITEM_COMPRA_AUTO_AUTOMOVIL_PRECIO DECIMAL(18, 0),
		PRIMARY KEY(ITEM_COMPRA_AUTO_NRO, ITEM_COMPRA_AUTO_ID)
	)
GO
	CREATE TABLE [FFAN].[ITEM_COMPRA_AUTOPARTE] (
		ITEM_COMPRA_AUTOPARTE_NRO DECIMAL(18, 0) NOT NULL FOREIGN KEY REFERENCES FFAN.COMPRA(COMPRA_NRO),
		ITEM_COMPRA_AUTOPARTE_CODIGO DECIMAL(18, 0) NOT NULL FOREIGN KEY REFERENCES FFAN.AUTOPARTE(AUTOPARTE_CODIGO),
		ITEM_COMPRA_AUTOPARTE_PRECIO DECIMAL(18, 0),
		ITEM_COMPRA_AUTOPARTE_CANT DECIMAL(18, 0),
		PRIMARY KEY (
			ITEM_COMPRA_AUTOPARTE_NRO,
			ITEM_COMPRA_AUTOPARTE_CODIGO
		)
	) CREATE TABLE [FFAN].[FACTURA] (
		FACTURA_NUMERO DECIMAL(18, 0) NOT NULL PRIMARY KEY,
		FACTURA_FECHA DATETIME2(3) NOT NULL,
		FACTURA_PRECIO_TOTAL DECIMAL(18, 2) NOT NULL,
		FACTURA_SUCURSAL_CIUDAD NVARCHAR(255),
		FACTURA_SUCURSAL_DIRECCION NVARCHAR(255),
		FACTURA_CLIENTE_ID DECIMAL(18, 0) NOT NULL FOREIGN KEY REFERENCES FFAN.CLIENTE(CLIENTE_ID),
		FACTURA_SUCURSAL_ID DECIMAL(18, 0) NOT NULL FOREIGN KEY REFERENCES FFAN.SUCURSAL(SUCURSAL_ID)
	)
GO
	CREATE TABLE [FFAN].[ITEM_FACTURA_AUTOPARTE] (
		ITEM_FACTURA_AUTOPARTE_NRO DECIMAL(18, 0) NOT NULL FOREIGN KEY REFERENCES FFAN.FACTURA(FACTURA_NUMERO),
		ITEM_FACTURA_AUTOPARTE_CODIGO DECIMAL(18, 0) NOT NULL FOREIGN KEY REFERENCES FFAN.AUTOPARTE(AUTOPARTE_CODIGO),
		ITEM_FACTURA_AUTOPARTE_PRECIO DECIMAL(18, 2),
		ITEM_FACTURA_AUTOPARTE_CANT DECIMAL(18, 0),
		PRIMARY KEY (
			ITEM_FACTURA_AUTOPARTE_NRO,
			ITEM_FACTURA_AUTOPARTE_CODIGO
		)
	)
GO
	CREATE TABLE [FFAN].[ITEM_FACTURA_AUTOMOVIL] (
		ITEM_FACTURA_AUTOMOVIL_NRO DECIMAL(18, 0) NOT NULL FOREIGN KEY REFERENCES FFAN.FACTURA(FACTURA_NUMERO),
		ITEM_FACTURA_AUTOMOVIL_ID DECIMAL(18, 0) NOT NULL FOREIGN KEY REFERENCES FFAN.AUTOMOVIL(AUTO_ID),
		ITEM_FACTURA_AUTOMOVIL_PRECIO DECIMAL(18, 2),
		PRIMARY KEY (
			ITEM_FACTURA_AUTOMOVIL_NRO,
			ITEM_FACTURA_AUTOMOVIL_ID
		)
	)
GO
	/*
	 ALEXIS : AUTOMOVIL Y TODAS LAS FK DE AUTOMOVIL
	 NACHO: FACTURA + ITEM FACTURA AUTOPARTE E ITEM FACTURA AUTOMOVIL
	 FACU: COMPRA + ITEM COMPRA AUTOPARTE E ITEM COMPRA AUTOMOVIL + ORDENAR SCRIPT
	 FEDE: SUCURSAL + CLIENTE 
	 */
INSERT INTO
	FFAN.CLIENTE
SELECT
	DISTINCT CLIENTE_APELLIDO,
	CLIENTE_NOMBRE,
	CLIENTE_DIRECCION,
	CLIENTE_DNI,
	CLIENTE_FECHA_NAC,
	CLIENTE_MAIL
FROM
	GD_ESQUEMA.MAESTRA
WHERE
	CLIENTE_DNI IS NOT NULL
UNION
SELECT
	DISTINCT FAC_CLIENTE_APELLIDO,
	FAC_CLIENTE_NOMBRE,
	FAC_CLIENTE_DIRECCION,
	FAC_CLIENTE_DNI,
	FAC_CLIENTE_FECHA_NAC,
	FAC_CLIENTE_MAIL
FROM
	GD_ESQUEMA.MAESTRA
WHERE
	FAC_CLIENTE_DNI IS NOT NULL
GO
INSERT INTO
	FFAN.SUCURSAL
SELECT
	DISTINCT SUCURSAL_DIRECCION,
	SUCURSAL_MAIL,
	SUCURSAL_TELEFONO,
	SUCURSAL_CIUDAD
FROM
	GD_ESQUEMA.MAESTRA
WHERE
	SUCURSAL_DIRECCION IS NOT NULL
UNION
SELECT
	DISTINCT FAC_SUCURSAL_DIRECCION,
	FAC_SUCURSAL_MAIL,
	FAC_SUCURSAL_TELEFONO,
	FAC_SUCURSAL_CIUDAD
FROM
	GD_ESQUEMA.MAESTRA
WHERE
	FAC_SUCURSAL_DIRECCION IS NOT NULL
GO
INSERT INTO
	FFAN.TIPO_CAJA
SELECT
	GD_ESQUEMA.MAESTRA.TIPO_CAJA_CODIGO,
	GD_ESQUEMA.MAESTRA.TIPO_CAJA_DESC
FROM
	GD_ESQUEMA.MAESTRA
WHERE
	TIPO_CAJA_CODIGO IS NOT NULL
GROUP BY
	GD_ESQUEMA.MAESTRA.TIPO_CAJA_CODIGO,
	GD_ESQUEMA.MAESTRA.TIPO_CAJA_DESC
GO
INSERT INTO
	FFAN.TIPO_AUTO
SELECT
	GD_ESQUEMA.MAESTRA.TIPO_AUTO_CODIGO,
	GD_ESQUEMA.MAESTRA.TIPO_AUTO_DESC
FROM
	GD_ESQUEMA.MAESTRA
WHERE
	TIPO_AUTO_CODIGO IS NOT NULL
GROUP BY
	GD_ESQUEMA.MAESTRA.TIPO_AUTO_CODIGO,
	GD_ESQUEMA.MAESTRA.TIPO_AUTO_DESC
GO
INSERT INTO
	FFAN.TIPO_MOTOR
SELECT
	DISTINCT TIPO_MOTOR_CODIGO,
	'DESCRIPCION_' + CONVERT(VARCHAR(4), TIPO_MOTOR_CODIGO)
FROM
	GD_ESQUEMA.MAESTRA
WHERE
	TIPO_MOTOR_CODIGO IS NOT NULL
GO
INSERT INTO
	FFAN.MODELO
SELECT
	GD_ESQUEMA.MAESTRA.MODELO_CODIGO,
	GD_ESQUEMA.MAESTRA.MODELO_NOMBRE,
	GD_ESQUEMA.MAESTRA.MODELO_POTENCIA
FROM
	GD_ESQUEMA.MAESTRA
WHERE
	GD_ESQUEMA.MAESTRA.MODELO_CODIGO IS NOT NULL
GROUP BY
	GD_ESQUEMA.MAESTRA.MODELO_CODIGO,
	GD_ESQUEMA.MAESTRA.MODELO_NOMBRE,
	GD_ESQUEMA.MAESTRA.MODELO_POTENCIA
GO
INSERT INTO
	FFAN.TIPO_TRANSMISION
SELECT
	GD_ESQUEMA.MAESTRA.TIPO_TRANSMISION_CODIGO,
	GD_ESQUEMA.MAESTRA.TIPO_TRANSMISION_DESC
FROM
	GD_ESQUEMA.MAESTRA
WHERE
	TIPO_TRANSMISION_CODIGO IS NOT NULL
GROUP BY
	GD_ESQUEMA.MAESTRA.TIPO_TRANSMISION_CODIGO,
	GD_ESQUEMA.MAESTRA.TIPO_TRANSMISION_DESC
GO
INSERT INTO
	FFAN.FABRICANTE (FFAN.FABRICANTE.FABRICANTE_NOMBRE)
SELECT
	DISTINCT(GD_ESQUEMA.MAESTRA.FABRICANTE_NOMBRE)
FROM
	GD_ESQUEMA.MAESTRA
WHERE
	GD_ESQUEMA.MAESTRA.FABRICANTE_NOMBRE IS NOT NULL
GO
INSERT INTO
	FFAN.AUTOMOVIL (
		AUTO_PATENTE,
		AUTO_FECHA_ALTA,
		AUTO_CANT_KMS,
		AUTO_NRO_CHASIS,
		AUTO_NRO_MOTOR,
		AUTO_MODELO_CODIGO,
		AUTO_TIPO_CAJA_CODIGO,
		AUTO_TIPO_MOTOR_CODIGO,
		AUTO_TIPO_TRANSMISION,
		AUTO_TIPO_CODIGO,
		AUTO_FABRICANTE_CODIGO
	)
SELECT
	M.AUTO_PATENTE,
	M.AUTO_FECHA_ALTA,
	M.AUTO_CANT_KMS,
	M.AUTO_NRO_CHASIS,
	M.AUTO_NRO_MOTOR,
	M.MODELO_CODIGO,
	M.TIPO_CAJA_CODIGO,
	M.TIPO_MOTOR_CODIGO,
	M.TIPO_TRANSMISION_CODIGO,
	M.TIPO_AUTO_CODIGO,
	F.FABRICANTE_CODIGO
FROM
	GD_ESQUEMA.MAESTRA M,
	FFAN.FABRICANTE F
WHERE
	M.FABRICANTE_NOMBRE = F.FABRICANTE_NOMBRE
	AND M.AUTO_PATENTE IS NOT NULL
GROUP BY
	M.AUTO_PATENTE,
	M.AUTO_FECHA_ALTA,
	M.AUTO_CANT_KMS,
	M.AUTO_NRO_CHASIS,
	M.AUTO_NRO_MOTOR,
	M.MODELO_CODIGO,
	M.TIPO_CAJA_CODIGO,
	M.TIPO_MOTOR_CODIGO,
	M.TIPO_TRANSMISION_CODIGO,
	M.TIPO_AUTO_CODIGO,
	F.FABRICANTE_CODIGO
GO
INSERT INTO
	FFAN.AUTOPARTE
SELECT
	DISTINCT AUTO_PARTE_CODIGO,
	AUTO_PARTE_DESCRIPCION,
	(
		SELECT
			FAB.FABRICANTE_CODIGO
		FROM
			FFAN.FABRICANTE FAB
		WHERE
			FAB.FABRICANTE_NOMBRE = MAESTRA.FABRICANTE_NOMBRE
	),
	(
		SELECT
			MODEL.MODELO_CODIGO
		FROM
			FFAN.MODELO MODEL
		WHERE
			MODELO_NOMBRE = MAESTRA.MODELO_NOMBRE
			AND MODEL.MODELO_POTENCIA = MAESTRA.MODELO_POTENCIA
	)
FROM
	GD_ESQUEMA.MAESTRA MAESTRA
WHERE
	AUTO_PARTE_CODIGO IS NOT NULL
GO
	--MIGRACION COMPRA 
INSERT INTO
	FFAN.COMPRA
SELECT
	T1.COMPRA_NRO,
	T1.COMPRA_FECHA,
	(
		SELECT
			C.CLIENTE_ID
		FROM
			FFAN.CLIENTE C
		WHERE
			C.CLIENTE_DNI = T1.CLIENTE_DNI
			AND C.CLIENTE_APELLIDO = T1.CLIENTE_APELLIDO
	) COMPRA_CLIENTE,
	SUM(T1.COMPRA_PRECIO * ISNULL(COMPRA_CANT, 1)) COMPRA_PRECIO_TOTAL,
	(
		SELECT
			S.SUCURSAL_ID
		FROM
			FFAN.SUCURSAL S
		WHERE
			S.SUCURSAL_DIRECCION = T1.SUCURSAL_DIRECCION
			AND S.SUCURSAL_CIUDAD = T1.SUCURSAL_CIUDAD
	) COMPRA_SUCURSAL_ID,
	SUCURSAL_DIRECCION COMPRA_SUCURSAL_DIRECCION,
	SUCURSAL_CIUDAD COMPRA_SUCURSAL_DIRECCION
FROM
	GD_ESQUEMA.MAESTRA T1
WHERE
	T1.COMPRA_NRO IS NOT NULL
	AND T1.FACTURA_NRO IS NULL
GROUP BY
	T1.COMPRA_NRO,
	T1.COMPRA_FECHA,
	T1.CLIENTE_DNI,
	T1.CLIENTE_APELLIDO,
	T1.SUCURSAL_DIRECCION,
	T1.SUCURSAL_CIUDAD
GO
	--MIGRACION ITEM_COMPRA_AUTOPARTE 
INSERT INTO
	FFAN.ITEM_COMPRA_AUTOPARTE
SELECT
	COMPRA_NRO,
	AUTO_PARTE_CODIGO,
	COMPRA_PRECIO,
	SUM(COMPRA_CANT)
FROM
	GD_ESQUEMA.MAESTRA
WHERE
	COMPRA_NRO IS NOT NULL
	AND AUTO_PARTE_CODIGO IS NOT NULL
	AND FACTURA_NRO IS NULL
GROUP BY
	COMPRA_NRO,
	AUTO_PARTE_CODIGO,
	COMPRA_PRECIO
GO
	--MIGRACION ITEM_COMPRA_AUTOMOVIL
INSERT INTO
	FFAN.ITEM_COMPRA_AUTOMOVIL
SELECT
	T1.COMPRA_NRO,
	(
		SELECT
			AUT.AUTO_ID
		FROM
			FFAN.AUTOMOVIL AUT
		WHERE
			AUT.AUTO_PATENTE = T1.AUTO_PATENTE
			AND AUT.AUTO_NRO_CHASIS = T1.AUTO_NRO_CHASIS
	) AUTOID,
	COMPRA_PRECIO
FROM
	GD_ESQUEMA.MAESTRA T1
WHERE
	T1.COMPRA_NRO IS NOT NULL
	AND T1.AUTO_NRO_MOTOR IS NOT NULL
	AND T1.FACTURA_NRO IS NULL
	AND T1.AUTO_NRO_CHASIS IS NOT NULL
GO
INSERT INTO
	FFAN.FACTURA
SELECT
	MAESTRA.FACTURA_NRO,
	MAESTRA.FACTURA_FECHA,
	SUM(
		MAESTRA.PRECIO_FACTURADO * ISNULL(CANT_FACTURADA, 1)
	) FACTURA_TOTAL,
	FAC_SUCURSAL_CIUDAD FACTURA_SUCURSAL_DIRECCION,
	FAC_SUCURSAL_DIRECCION FACTURA_SUCURSAL_DIRECCION,
	(
		SELECT
			C.CLIENTE_ID
		FROM
			FFAN.CLIENTE C
		WHERE
			C.CLIENTE_DNI = MAESTRA.FAC_CLIENTE_DNI
			AND C.CLIENTE_APELLIDO = MAESTRA.FAC_CLIENTE_APELLIDO
	) FACTURA_CLIENTE,
	(
		SELECT
			S.SUCURSAL_ID
		FROM
			FFAN.SUCURSAL S
		WHERE
			S.SUCURSAL_DIRECCION = MAESTRA.FAC_SUCURSAL_DIRECCION
			AND S.SUCURSAL_CIUDAD = MAESTRA.FAC_SUCURSAL_CIUDAD
	) FACTURA_SUCURSAL_ID
FROM
	GD_ESQUEMA.MAESTRA MAESTRA
WHERE
	MAESTRA.FACTURA_NRO IS NOT NULL
GROUP BY
	MAESTRA.FACTURA_NRO,
	MAESTRA.FACTURA_FECHA,
	MAESTRA.FAC_CLIENTE_DNI,
	MAESTRA.FAC_CLIENTE_APELLIDO,
	MAESTRA.FAC_SUCURSAL_CIUDAD,
	MAESTRA.FAC_SUCURSAL_DIRECCION
GO
INSERT INTO
	FFAN.ITEM_FACTURA_AUTOPARTE
SELECT
	FACTURA_NRO,
	AUTO_PARTE_CODIGO,
	PRECIO_FACTURADO,
	SUM(CANT_FACTURADA)
FROM
	GD_ESQUEMA.MAESTRA
WHERE
	FACTURA_NRO IS NOT NULL
	AND AUTO_PARTE_CODIGO IS NOT NULL
	AND COMPRA_NRO IS NULL
GROUP BY
	FACTURA_NRO,
	AUTO_PARTE_CODIGO,
	PRECIO_FACTURADO
GO
INSERT INTO
	FFAN.ITEM_FACTURA_AUTOMOVIL
SELECT
	DISTINCT FACTURA_NRO,
	(
		SELECT
			AUT.AUTO_ID
		FROM
			FFAN.AUTOMOVIL AUT
		WHERE
			AUT.AUTO_PATENTE = MAESTRA.AUTO_PATENTE
			AND AUT.AUTO_NRO_CHASIS = MAESTRA.AUTO_NRO_CHASIS
	) AUTOID,
	PRECIO_FACTURADO
FROM
	GD_ESQUEMA.MAESTRA MAESTRA
WHERE
	FACTURA_NRO IS NOT NULL
	AND AUTO_PATENTE IS NOT NULL
